version: '3.7'

services:
  rustdesk:
    image: rustdesk/rustdesk-server
    container_name: rustdesk
    ports:
      - "21115:21115"
      - "21116:21116"
      - "21116:21116/udp"
      - "21118:21118"
    volumes:
      - /share/CACHEDEV1_DATA/Container/rustdeskhbbs:/root:rw
    restart: unless-stopped
